"""Reverse-engineered GitSkins wordmark block font.

Each letter is a 12-row ASCII glyph (monospace block characters: S, +, `,
:, -, = building a beveled 3D look) extracted from 8 real downloaded
wordmark cards - LINUS, DAN, TOM, CHRIS, YEHUDA KATZ, JEREMY, FABIEN,
BORGES DEV - by finding columns that are blank across all 12 rows
simultaneously (letter boundary = a fully-blank column). 22 of 26 letters
came out of that extraction, verified against every source name's exact
letter count with zero mismatches. P, Q, W, X were never covered by any
of the 8 real names, so they're hand-drawn using the same stroke
vocabulary (reusing chunks of R's loop for P, O's curve for Q, N's
diagonal for W/X) - same family, not a real capture.
"""

LETTERS = {
    "A": [
        '   SSSS SSSSS   ',
        '   :++++++++`   ',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        ':SSSSSS SSSSSSS`',
        ':S`++++++++++:S`',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        ':+`          :+`',
        '++-          ++-',
    ],
    "B": [
        ' SSSSSSSSSSSS   ',
        ':-S++++++++``   ',
        ':-`++++++++-:-``',
        ':-``SSSSSSSS:+`-',
        ':-S++++++++``   ',
        ':-`++++++++-:-``',
        ':-``        :-``',
        ':-``        :-``',
        ':-``        :-``',
        ':-``SSSSSSSS:+`-',
        ':++++++++++``   ',
        '+++++++++++-    ',
    ],
    "C": [
        '    SSSSSSSSSSSS',
        '   :++++++++++``',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':+`-SSSSSSSSSSSS',
        '   :++++++++++``',
        '   +++++++++++- ',
    ],
    "D": [
        ' SSSSSSSSSSSS   ',
        ':-S+++++++++`   ',
        '::``         :S`',
        '::``         :S`',
        '::``         :S`',
        '::``         :S`',
        ':-``         :S`',
        ':-``         :S`',
        ':-``         :S`',
        ':-``SSSSSSSSS:+`',
        '::++++++++++`   ',
        '++++++++++++-   ',
    ],
    "E": [
        '               ',
        '::SS++++++++++`',
        '::`+++++++++++-',
        ' :``SSSSSSSSS  ',
        ' :SS+++++++``  ',
        ' :`++++++++-   ',
        ' :``           ',
        ' :``           ',
        ' :``           ',
        ' :``SSSSSSSSSSS',
        ' :++++++++++++`',
        ' +++++++       ',
    ],
    "F": [
        ' SSSSSSSSSSSSSSS',
        ':-S+++++++++++``',
        ':-`+++++++++++- ',
        ':-``SSSSSSSSS   ',
        ':-S++++++++``   ',
        ':-`++++++++-    ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':+``            ',
        '++-             ',
    ],
    "G": [
        '   SSSSSSSSSSSS',
        '   :++++++++++`',
        '-S`+++++++++++-',
        ':S`            ',
        ':S`            ',
        ':S`   :SSSSSSS`',
        ':S`   :+++++:S`',
        ':S`         :S`',
        ':S`         :S`',
        '++-SSSSSSSSS:S`',
        '   :++++++++++`',
        '               ',
    ],
    "H": [
        ' SSS         SSS',
        '::``         :S`',
        '::``         :S`',
        '::``SSSSSSSSS:S`',
        '::S++++++++++SS`',
        '::`+++ ++++++:S`',
        '::``         :S`',
        '::``         :S`',
        '::``         :S`',
        '::``         :S`',
        '::``         :+`',
        '++--         ++-',
    ],
    "I": [
        ' SSSSSSSSSSSSSSS',
        ':++++++SSS+++++`',
        '       :S`      ',
        '       :S`      ',
        '       :S`      ',
        '       :S`      ',
        '       :S`      ',
        '       :S`      ',
        '       :S`      ',
        ' SSSSSS:S`SSSSSS',
        '::+++++++++++++`',
        '+++++++++++++++-',
    ],
    "J": [
        ' SSSSSSSSSSSSSSS',
        ':+++++++++SS++`-',
        '+++++++++:-`++- ',
        '         :-``   ',
        '         :-``   ',
        '         :-``   ',
        ' SSS     :-``   ',
        ':-``     :-``   ',
        ':-``     :-``   ',
        ':+`-SSSSS:+`-   ',
        '   :++++``      ',
        '   +++++-       ',
    ],
    "K": [
        'SS`        SS` ',
        'S:``        :+`',
        'S:``     -S`++-',
        'S:``  SSS:+`   ',
        'S:``  :+`      ',
        '-:S`S`++-      ',
        '-:``+`SSS      ',
        '-:``  :+`      ',
        '-:``     :S`   ',
        '-:``     ++-SSS',
        '-:+`        :+`',
        '               ',
    ],
    "L": [
        ' SSS            ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':-``            ',
        ':-``SSSSSSSSSSSS',
        ':+++++++++++++``',
        '++++++++++++++--',
    ],
    "M": [
        'SSS         SSS ',
        ':S`         ::``',
        ':SSSS`   ::SSS``',
        ':S`++-SSS++++:``',
        ':S`   :+``  ::``',
        ':S`         ::``',
        ':S`         ::``',
        ':S`         ::``',
        ':S`         ::``',
        ':S`         ::``',
        ':+`         ::``',
        '++-         +++-',
    ],
    "N": [
        'SSS         SSS',
        ':S`         :S`',
        ':SSSS`      :S`',
        ':S`++-SSS   :S`',
        ':S`   :+`   :S`',
        ':S`   ++-:SS:S`',
        ':S`      :++:S`',
        ':S`         :S`',
        ':S`         :S`',
        ':S`         :S`',
        ':+`         :+`',
        '++-         ++-',
    ],
    "O": [
        '   SSSS SSSSS   ',
        '   :++++++++`   ',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        ':+`SSSS SSSSS:+`',
        '   :+++ ++++`   ',
        '   +++++++++-   ',
    ],
    "P": [
        'SSSSSSSSSSSS   ',
        ':SS++++++++`   ',
        ':S`         :S`',
        ':S`         :S`',
        ':S`         :+`',
        ':S`SSSSSSSS`++-',
        ':S`            ',
        ':S`            ',
        ':S`            ',
        ':S`            ',
        ':+`            ',
        '++-            ',
    ],
    "Q": [
        '   SSSS SSSSS   ',
        '   :++++++++`   ',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        ':S`          :S`',
        '   :+++S++++`  ',
        '   +++++`SS+-  ',
        '        `++-   ',
    ],
    "R": [
        'SSSSSSSSSSSS   ',
        ':SS++++++++`   ',
        ':S`         :S`',
        ':S`         :S`',
        ':S`         :+`',
        ':S`SSSSSSSS`++-',
        ':S`+++:S`++`   ',
        ':S`   :+`      ',
        ':S`   ++-:S`   ',
        ':S`      :+`SSS',
        ':+`         :+`',
        '++-         ++-',
    ],
    "S": [
        '   SSSSSSSSSSSS ',
        '   +:++++++++++`',
        '::``            ',
        '::``            ',
        '::+`            ',
        ' ++-:SSSSSS``   ',
        '   +:+++++++`SS ',
        '            -:``',
        '            -:``',
        'SSSSSSSSSSSS+:+`',
        '::++++++++++`   ',
        '++++++++++++-   ',
    ],
    "T": [
        ' SSSSSSSSSSSSSSS',
        ':++++++SSS+++++`',
        '      ::S`      ',
        '      ::S`      ',
        '      ::S`      ',
        '      ::S`      ',
        '      ::S`      ',
        '      ::S`      ',
        '       :S`      ',
        '       :S`      ',
        '       :+`      ',
        '       ++-      ',
    ],
    "U": [
        'SSS         SSS ',
        ':S`         ::``',
        ':S`         ::``',
        ':S`         ::``',
        ':S`         ::``',
        ':S`         ::``',
        ':S`         ::``',
        ':S`         ::``',
        ':S`         :S``',
        ':+`SSSSSSSSS:++`',
        '   :+++++++`    ',
        '   ++++++++-    ',
    ],
    "V": [
        'SSS        SSS ',
        ':S`        -:``',
        ':S`        -:``',
        ':S`        -:``',
        ':S`        -:``',
        ':S`        -:``',
        ':S`        -:``',
        ':+`        -:+`',
        '   :S`  -:``   ',
        '   ++-SS+++-   ',
        '     S:+`      ',
        '               ',
    ],
    "W": [
        'SSS        SSS ',
        ':S`        :S` ',
        ':S`        :S` ',
        ':S`  SSSS  :S` ',
        ':S` :S``S` :S` ',
        ':S`:S`  `S`:S` ',
        ':S`S`    `S:S` ',
        ':SS`      `SS` ',
        ':S`        :S` ',
        '`+`        `+` ',
        ' +-        +-  ',
        '                ',
    ],
    "X": [
        'SSS         SSS',
        ':+S`       `S+:',
        '  :+S`   `S+:  ',
        '    :+S`S+:    ',
        '      :S`      ',
        '     :S`S`     ',
        '    :S`  `S`   ',
        '   :S`    `S`  ',
        '  :S`      `S` ',
        ' :S`        `S`',
        '++`          `+',
        '+-            -',
    ],
    "Y": [
        '               ',
        '::``        :S`',
        '::``        :S`',
        ':+``SSS   SS:+`',
        '   :+``  :+`S  ',
        '   ++-:-`++-   ',
        '      :-``     ',
        '      :-``     ',
        '      :-``     ',
        '      :-``     ',
        '      :+``     ',
        '      ++=      ',
    ],
    "Z": [
        'SSSSSSSSSSSSS`` ',
        ' :++++++++++SS``',
        ' ++++++++++++:``',
        '         SSS-:+`',
        '         -:+`   ',
        '      -:``++-   ',
        '   SSS+:+`      ',
        '   S:+`         ',
        ' :S`            ',
        ' :S`SSSSSSSSSSS ',
        ' :+++++++++++++`',
        '                ',
    ],
}

ROWS = 12
LETTER_GAP = 2   # blank columns between letters within a word
WORD_GAP = 6     # blank columns between words


def render_block(text):
    """text: e.g. 'BORGES DEV'. Returns a list of ROWS strings (the ASCII block)."""
    words = [w for w in text.upper().split(' ') if w]
    lines = [""] * ROWS
    for wi, word in enumerate(words):
        if wi > 0:
            for r in range(ROWS):
                lines[r] += " " * WORD_GAP
        for li, ch in enumerate(word):
            glyph = LETTERS.get(ch)
            if glyph is None:
                glyph = [" " * 10] * ROWS  # no glyph for this character (digits, symbols) - leave a gap, don't guess
            width = max(len(row) for row in glyph)
            if li > 0:
                for r in range(ROWS):
                    lines[r] += " " * LETTER_GAP
            for r in range(ROWS):
                lines[r] += glyph[r].ljust(width)
    maxlen = max(len(l) for l in lines)
    return [l.ljust(maxlen) for l in lines]